-- Crypto Trading Intelligence V1.4
-- Run this entire file in Supabase SQL Editor.
-- For passwordless personal use, enable Authentication -> Providers -> Anonymous Sign-Ins.
create extension if not exists pgcrypto;

create table if not exists public.watchlist (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  symbol text not null check (symbol ~ '^[A-Z0-9]+USDT$'),
  created_at timestamptz not null default now(),
  unique(user_id, symbol)
);

create table if not exists public.scan_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  timeframe text not null default '4h',
  price numeric not null,
  opportunity_score integer not null check (opportunity_score between 0 and 100),
  quality_score integer check (quality_score between 0 and 100),
  risk_score integer not null check (risk_score between 0 and 100),
  setup_status text,
  payload jsonb not null default '{}'::jsonb,
  scanned_at timestamptz not null default now(),
  scan_slot timestamptz
);

alter table public.scan_snapshots add column if not exists scan_slot timestamptz;
create unique index if not exists scan_snapshots_symbol_tf_slot_uidx
  on public.scan_snapshots(symbol, timeframe, scan_slot)
  where scan_slot is not null;
create index if not exists scan_snapshots_scanned_at_idx on public.scan_snapshots(scanned_at desc);
create index if not exists scan_snapshots_quality_idx on public.scan_snapshots(quality_score desc nulls last);

create table if not exists public.paper_trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  symbol text not null check (symbol ~ '^[A-Z0-9]+USDT$'),
  opened_at timestamptz not null default now(),
  status text not null default 'OPEN' check (status in ('OPEN','CLOSED')),
  entry numeric not null,
  stop numeric not null,
  tp1 numeric not null,
  tp2 numeric not null,
  quantity numeric not null,
  capital_idr numeric not null,
  risk_pct numeric not null,
  max_loss_idr numeric not null,
  usdt_idr numeric not null,
  quality_score integer not null,
  opportunity_score integer not null,
  risk_score integer not null,
  setup_status text not null,
  snapshot jsonb not null default '{}'::jsonb,
  evaluation jsonb,
  close_price numeric,
  closed_at timestamptz,
  realized_pnl_idr numeric,
  updated_at timestamptz not null default now()
);
create index if not exists paper_trades_user_opened_idx on public.paper_trades(user_id, opened_at desc);
create index if not exists paper_trades_status_idx on public.paper_trades(status, opened_at);

create table if not exists public.background_runs (
  id uuid primary key default gen_random_uuid(),
  job text not null check (job in ('validate','snapshot')),
  status text not null default 'RUNNING' check (status in ('RUNNING','SUCCESS','PARTIAL','FAILED')),
  processed integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists background_runs_job_started_idx on public.background_runs(job, started_at desc);

alter table public.watchlist enable row level security;
alter table public.scan_snapshots enable row level security;
alter table public.paper_trades enable row level security;
alter table public.background_runs enable row level security;

drop policy if exists "Users can view own watchlist" on public.watchlist;
drop policy if exists "Users can insert own watchlist" on public.watchlist;
drop policy if exists "Users can delete own watchlist" on public.watchlist;
create policy "Users can view own watchlist" on public.watchlist for select using (auth.uid() = user_id);
create policy "Users can insert own watchlist" on public.watchlist for insert with check (auth.uid() = user_id);
create policy "Users can delete own watchlist" on public.watchlist for delete using (auth.uid() = user_id);

drop policy if exists "Users can view own paper trades" on public.paper_trades;
drop policy if exists "Users can insert own paper trades" on public.paper_trades;
drop policy if exists "Users can update own paper trades" on public.paper_trades;
drop policy if exists "Users can delete own paper trades" on public.paper_trades;
create policy "Users can view own paper trades" on public.paper_trades for select using (auth.uid() = user_id);
create policy "Users can insert own paper trades" on public.paper_trades for insert with check (auth.uid() = user_id);
create policy "Users can update own paper trades" on public.paper_trades for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete own paper trades" on public.paper_trades for delete using (auth.uid() = user_id);

-- Market snapshots contain public market data only. Authenticated/anonymous users may read them.
drop policy if exists "Authenticated users can read scan snapshots" on public.scan_snapshots;
create policy "Authenticated users can read scan snapshots" on public.scan_snapshots
  for select using (auth.role() = 'authenticated');

-- background_runs is intentionally server-managed. The public dashboard reads a sanitized
-- status through /api/background-status, so no client RLS policy is required here.
-- Service-role requests bypass RLS for cron inserts/updates.
